[good]plesae make the sh file to automatically install librosa, cause:
(pnnx) root@C.19053167:~/icefall/egs/commonvoice/ASR/download/l2_arctic$ bash prepare_l2_arctic.sh --use-cn-accented-only --merge-into-dir ../concise-cv-ds-by-jimmy-1 --total-hours 2.5
Output directory ./l2_arctic_data does not exist. Will download the dataset.
Starting L2-Arctic dataset download and extraction...
Will only use Chinese-accented speakers
Running: python download_l2_arctic_ds_from_official_site.py --output-dir "./l2_arctic_data"  --total-hours 2.5 --use-cn-only
Traceback (most recent call last):
  File "download_l2_arctic_ds_from_official_site.py", line 33, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'